### ISSUE TITLE
Server crash after install SquidGamesPlus-2.0.sk

### ISSUE THREAD

**Issue by PappoYT** [MCLaraTeam/minigame-squidgames#2]
```
Paper 1.16.5
skript 2.6
skript-yaml 1.4
SquidGamesPlus 2.0
```

**Problem:** server crashes after install SquidGamesPlus-2.0.sk

**Step to reproduce:**

1. You must download the latest available version of Skript from the official website. **DONE**
2. Place the downloaded Skript .jar file into the /plugins folder. **DONE**
3. You must download the latest available version of SkriptYaml from the official website. **DONE**
4. Place the downloaded SkriptYaml .jar file into the /plugins folder. **DONE**
5. Start your server, which when loading Skript will generate a folder inside /plugins called skript. **DONE, without any problem**
6. Download the desired version of SquidGames or SquidGamesPlus. **DONE**
7. Insert the .sk file into the /plugins/skript/scripts folder. **DONE**
8. Restart the server. **DONE, but server crashes when restarted**

**Log:**
[https://mclo.gs/L3hIAsk](https://mclo.gs/L3hIAsk)

**Comment by MCLaraTeam** [comment]
It is not a bug you must insert your license. check your log.
[06:07:22] [Server thread/INFO]: [SquidGamesPlus] Loading license.
2832 | [06:07:22] [Server thread/INFO]: [SquidGamesPlus] Invalid license key.
